[package]
name = "cm-telemetry"
version = "1.0.1"
authors = ["Oscar Moreno <oscarmg99@gmail.com>"]
repository = "https://github.com/ozkar99/cm-telemetry"
readme = "README.md"
description = "Implementation of the telemetry UDP protocol for codemasters games"
license-file = "LICENSE"
edition = "2018"

[dependencies]
byteorder = "1"
